import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="ja">
        <body className={`${notoSans.className}`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <div style={{ marginLeft: "24px", marginTop: "24px" }}>
              <UserButton
                appearance={{
                  elements: {
                    userButtonTrigger: {
                      backgroundColor: "transparent",
                      boxShadow: "none",
                      "&:focus": {
                        boxShadow: "none",
                      },
                      "&:hover": {
                        backgroundColor: "transparent",
                      },
                    },
                    userButtonAvatarBox: {
                      backgroundColor: "transparent",
                    },
                    userButtonAvatarImage: {
                      content: "url('./person.svg')",
                    },
                  },
                }}
              />
            </div>
            <Toaster />
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
